linux/scripts: more informative error on build-prep failure

diff --git a/LINUX/scripts/np b/LINUX/scripts/np
--- a/LINUX/scripts/np
+++ b/LINUX/scripts/np
@@ -361,7 +361,6 @@ function build-prep()
 
 	[ -z "$dst" ] && return
 
-	exec 3>&1 4>&2 >$dst.log 2>&1
 	(
 		cd $dst
 		if [ -f $LINUX_CONFIGS/config-$v ]; then
@@ -371,8 +370,7 @@ function build-prep()
 			make allmodconfig
 		fi
 		make modules_prepare
-	)
-	exec 1>&3 2>&4
+	) >$dst.log 2>&1 || error "build-prep failed for linux $version. Please check $dst.log"
 	echo $dst
 }
 
