linux/configure: allow test on driver APIs
The drivers sources are now copied in the test build-dir, so
that tests can easily include driver header files when
needed.

diff --git a/LINUX/configure b/LINUX/configure
--- a/LINUX/configure
+++ b/LINUX/configure
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+TOPDIR=$PWD
+
 prefix=/usr/local
 cc=cc
 ld=ld
@@ -175,8 +177,10 @@ run_tests() {
 		ifneq (\$(KERNELRELEASE),)
 		obj-m := $TESTOBJS
 		else
-		all:
+		all: $get_drivers
 		$t	\$(MAKE) -C $ksrc M=\$\$PWD
+
+		-include $TOPDIR/drivers.mak
 		endif
 	EOF
 	(
@@ -327,6 +331,81 @@ via a generic adapter at reduced performance."
 		EOF
 	fi
 fi
+
+
+###############################################################
+# Makefile creation
+###############################################################
+
+# here we select the patches for the drivers and create the
+# main Makefile. The Makefile is obtained from Makefile.in
+# with some values replaced in (mainly the kernel directory).
+# The final Makefile will include drivers.mak, which is also
+# created here. drivers.mak will contain a get-driver and
+# clear-driver target for each of the available drivers.
+
+patches=
+s_drivers=
+get_drivers=
+clean_drivers=
+mod_list=
+if [ -z "$nodrivers" ]; then
+	# produce a list of applicable patches for this version
+	[ -d patches ] || { rm -f patches; ln -s final-patches patches; }
+	# the selection is based only on the kernel version
+	patches=$(cd patches; ls diff--* | awk -v v=$lin_ver -F -- '($3 <= v"") && (v"" < $4)')
+fi
+
+rm -f drivers.mak
+source $ksrc/.config
+for p in $patches; do
+	# extract the driver name
+	driver=$(echo $p | awk -F -- '{ print $2 }')
+	# find the driver sources
+	s=$(find $src/drivers/ -name "$driver" -print -quit)
+	[ -n "$s" ] || { echo "WARNING: $driver sources not found"; continue; }
+	drv_conf="CONFIG_$(basename $driver .c | tr a-z A-Z)"
+	[ "${!drv_conf}" = m ] || {
+		echo "WARNING: $drv_conf=m not set in $ksrc/.config, skipping $driver"
+		continue
+	}
+	mod_list="$drv_conf=m $mod_list"
+	# add the driver related targets to drivers.mak
+	$t=	# prevent -EOF to eat the make TAB
+	cat >> drivers.mak <<-EOF
+		get-$driver:
+		$t	cp -Rp $s .
+		$t	if [ -f patches/$p ]; then patch --posix --quiet --force -p1 < patches/$p; fi
+		$t	touch get-$driver
+
+		clean-$driver:
+		$t	rm -rf $driver get-$driver
+
+	EOF
+	s_drivers="$driver $s_drivers"
+	get_drivers="get-$driver $get_drivers"
+	clean_drivers="clean-$driver $clean_drivers"
+done
+# add some convenience cumulative targets
+cat >> drivers.mak <<-EOF
+	.PHONY: get-drivers clean-drivers
+	get-drivers: $get_drivers
+	clean-drivers: $clean_drivers
+EOF
+
+# create Makefile
+sed \
+	-e "s|@KSRC@|$ksrc|g" \
+	-e "s|@SRC@|$src|g" \
+	-e "s|@KOPTS@|$kopts|g" \
+	-e "s|@LIN_VER@|$lin_ver|g" \
+	-e "s|@MOD_LIST@|$mod_list|g" \
+	-e "s|@PATCHES@|$(echo $patches)|g" \
+	-e "s|@S_DRIVERS@|$(echo $s_drivers)|g" \
+	-e "s|@APPS_CC@|$cc|g" \
+	-e "s|@APPS_LD@|$ld|g" \
+	-e "s|@PREFIX@|$prefix|g" \
+	Makefile.in > Makefile
 
 
 #################################################
@@ -575,80 +654,6 @@ cat >> $configh <<-EOF
 
 	#endif
 EOF
-
-###############################################################
-# Makefile creation
-###############################################################
-
-# here we select the patches for the drivers and create the
-# main Makefile. The Makefile is obtained from Makefile.in
-# with some values replaced in (mainly the kernel directory).
-# The final Makefile will include drivers.mak, which is also
-# created here. drivers.mak will contain a get-driver and
-# clear-driver target for each of the available drivers.
-
-patches=
-s_drivers=
-get_drivers=
-clean_drivers=
-mod_list=
-if [ -z "$nodrivers" ]; then
-	# produce a list of applicable patches for this version
-	[ -d patches ] || { rm -f patches; ln -s final-patches patches; }
-	# the selection is based only on the kernel version
-	patches=$(cd patches; ls diff--* | awk -v v=$lin_ver -F -- '($3 <= v"") && (v"" < $4)')
-fi
-
-rm -f drivers.mak
-source $ksrc/.config
-for p in $patches; do
-	# extract the driver name
-	driver=$(echo $p | awk -F -- '{ print $2 }')
-	# find the driver sources
-	s=$(find $src/drivers/ -name "$driver" -print -quit)
-	[ -n "$s" ] || { echo "WARNING: $driver sources not found"; continue; }
-	drv_conf="CONFIG_$(basename $driver .c | tr a-z A-Z)"
-	[ "${!drv_conf}" = m ] || {
-		echo "WARNING: $drv_conf=m not set in $ksrc/.config, skipping $driver"
-		continue
-	}
-	mod_list="$drv_conf=m $mod_list"
-	# add the driver related targets to drivers.mak
-	$t=	# prevent -EOF to eat the make TAB
-	cat >> drivers.mak <<-EOF
-		get-$driver:
-		$t	cp -Rp $s .
-		$t	patch --posix --quiet --force -p1 < patches/$p
-		$t	touch get-$driver
-
-		clean-$driver:
-		$t	rm -rf $driver get-$driver
-
-	EOF
-	s_drivers="$driver $s_drivers"
-	get_drivers="get-$driver $get_drivers"
-	clean_drivers="clean-$driver $clean_drivers"
-done
-# add some convenience cumulative targets
-cat >> drivers.mak <<-EOF
-	.PHONY: get-drivers clean-drivers
-	get-drivers: $get_drivers
-	clean-drivers: $clean_drivers
-EOF
-
-# create Makefile
-sed \
-	-e "s|@KSRC@|$ksrc|g" \
-	-e "s|@SRC@|$src|g" \
-	-e "s|@KOPTS@|$kopts|g" \
-	-e "s|@LIN_VER@|$lin_ver|g" \
-	-e "s|@MOD_LIST@|$mod_list|g" \
-	-e "s|@PATCHES@|$(echo $patches)|g" \
-	-e "s|@S_DRIVERS@|$(echo $s_drivers)|g" \
-	-e "s|@APPS_CC@|$cc|g" \
-	-e "s|@APPS_LD@|$ld|g" \
-	-e "s|@PREFIX@|$prefix|g" \
-	Makefile.in > Makefile
 
 
 report
